name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install --upgrade buildozer cython pip
      - name: Build APK
        run: cd ${{ github.workspace }} && buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GameTextTranslator-APK
          path: bin/*.apk
